#!/usr/bin/env bats
# T008 [026] — a real `specify extension add --dev` install into a fixture
# repository produces exactly the derived surface, member for member, in
# both directions (contracts/surface-derivation.md C3.1/C3.2).
#
# Fails today on the `.git` leak: `.extensionignore` does not yet exclude
# `.git/`, so the install copies this repository's history (research R5)
# into the consumer tree, and the diff below is non-empty until T011 lands.

setup() {
  ROOT="${BATS_TEST_DIRNAME}/../../.."
  # shellcheck source=tests/bash/helpers/consumer_fixture.bash
  source "${ROOT}/tests/bash/helpers/consumer_fixture.bash"
  # shellcheck source=packaging/lib/surface.sh
  source "${ROOT}/packaging/lib/surface.sh"
  fixture_require || skip "${FIXTURE_SKIP_REASON}"
  REPO=""
}

teardown() {
  # `[ -n "" ]` exits 1; as teardown's last command that turns a correctly
  # skipped test into a reported failure (bats treats a nonzero teardown
  # exit as a failure regardless of skip). Never let cleanup's own exit
  # status become the test's.
  [ -n "${REPO}" ] && fixture_cleanup "${REPO}"
  true
}

@test "a --dev install tree equals the derived surface, both directions (C3.1, C3.2)" {
  REPO="$(fixture_new_repo)"
  run bash -c "cd '${REPO}' && specify extension add --dev '${ROOT}' --force"
  [ "$status" -eq 0 ]

  installed_dir="${REPO}/.specify/extensions/jira"
  [ -d "${installed_dir}" ]

  # `.specify-dev/agent-commands/…` is generated by the installer AFTER the
  # copy (research R5, data-model.md "Reference copy" contaminants table) —
  # never part of the surface, and legitimately present after every --dev
  # install, so it is excluded here rather than treated as a mismatch.
  installed="$(cd "${installed_dir}" && find . -type f -not -path './.specify-dev/*' \
    | sed 's|^\./||' | LC_ALL=C sort)"
  expected="$(packaging_derive_surface | LC_ALL=C sort)"

  diff <(printf '%s\n' "${expected}") <(printf '%s\n' "${installed}")
}
