# T037 [US4] — The documented procedures invoke a bridge that exists, PowerShell
# port. Twin of tests/bash/ci/test_agent_doc_invocation.bats (FR-014, R6).
#
# `specify extension add` copies this repository into the consuming repository's
# `.specify/extensions/jira/` and installs NOTHING on the machine: no binary, no
# PATH entry, no shell profile edit. Yet both command documents used to instruct
# the assistant to run `spec-kit-jira config` and `spec-kit-jira feature` as bare
# names. In a consuming repository no such command exists — which is precisely
# the reported "spec-kit-jira CLI not installed" symptom, generated by following
# the instructions as written.
#
# So the check is on the DOCUMENTS, not on the scripts: they are what the
# assistant follows, and a wrong instruction there produces a wrong action every
# time, on every machine. It runs on both ports because a Windows developer
# reading a document that only names the Bash path is just as stuck.

BeforeAll {
    $script:Root = (Resolve-Path (Join-Path $PSScriptRoot '../../..')).Path
    $script:Docs = Get-ChildItem -LiteralPath (Join-Path $script:Root 'commands') -Filter '*.md' -File | Sort-Object Name
    $script:BashEntry = '.specify/extensions/jira/scripts/bash/spec-kit-jira.sh'
    $script:PwshEntry = '.specify/extensions/jira/scripts/powershell/spec-kit-jira.ps1'
}

Describe 'Command documents invoke a bridge that exists' {
    It 'has three command documents, one per declared command' {
        $script:Docs.Count | Should -Be 3
    }

    It 'invokes no bare spec-kit-jira name (FR-014)' {
        foreach ($doc in $script:Docs) {
            $text = Get-Content -Raw -LiteralPath $doc.FullName
            foreach ($line in ($text -split "`r?`n")) {
                if ($line -match '(^|[^/])spec-kit-jira(\.sh|\.ps1)?\s+(config|reconcile|mention|feature)\b') {
                    throw "$($doc.Name) invokes the bridge by a bare name: $($line.Trim())"
                }
            }
        }
    }

    It 'names BOTH per-port entry points in every document (FR-013, R6)' {
        # Naming only one port would leave the operator on the other one with an
        # instruction that cannot work — and the two ports are required to behave
        # identically (Constitution VI).
        foreach ($doc in $script:Docs) {
            $text = Get-Content -Raw -LiteralPath $doc.FullName
            $text | Should -Match ([regex]::Escape($script:BashEntry))
            $text | Should -Match ([regex]::Escape($script:PwshEntry))
        }
    }

    It 'states the host-selection rule in every document (FR-013)' {
        # Two paths with no rule for choosing between them is an invitation to guess.
        foreach ($doc in $script:Docs) {
            (Get-Content -Raw -LiteralPath $doc.FullName) | Should -Match '(?i)windows'
        }
    }

    It 'spells paths that exist (FR-012)' {
        Test-Path -LiteralPath (Join-Path $script:Root 'scripts/bash/spec-kit-jira.sh') | Should -BeTrue
        Test-Path -LiteralPath (Join-Path $script:Root 'scripts/powershell/spec-kit-jira.ps1') | Should -BeTrue
    }

    It 'instructs no machine-wide install anywhere (FR-008)' {
        foreach ($doc in $script:Docs) {
            $text = Get-Content -Raw -LiteralPath $doc.FullName
            $text | Should -Not -Match '(brew install spec-kit|npm i(nstall)? -g|pip install spec-kit|add to your PATH|export PATH=)'
        }
    }

    It 'carries the bash prefix on every invocation, never on a bare filename (C2)' {
        # A path followed by a command or flag is an invocation and MUST be
        # preceded by `bash `; a path followed by nothing is a filename and
        # MUST NOT be — conflating the two produces "the bridge entry point
        # bash …/… was not found".
        $invocation = [regex]'\.specify/extensions/jira/scripts/bash/spec-kit-jira\.sh\s+(config|reconcile|mention|feature|--help)'
        foreach ($doc in $script:Docs) {
            $text = Get-Content -Raw -LiteralPath $doc.FullName
            foreach ($line in ($text -split "`r?`n")) {
                $isInvocation = $invocation.IsMatch($line)
                $hasPrefix = $line.Contains('bash .specify/extensions/jira/scripts/bash/spec-kit-jira.sh')
                if ($isInvocation -and -not $hasPrefix) {
                    throw "$($doc.Name): invocation missing the bash prefix (C2): $($line.Trim())"
                }
                if ($hasPrefix -and -not $isInvocation) {
                    throw "$($doc.Name): a bash-prefixed occurrence is not an invocation (C2): $($line.Trim())"
                }
            }
        }
    }
}
