#!/usr/bin/env bats
# T036 [US4] — The documented procedures invoke a bridge that exists (FR-014,
# research R6).
#
# `specify extension add` copies this repository into the consuming repository's
# `.specify/extensions/jira-mirror/` and installs NOTHING on the machine: no binary, no
# PATH entry, no shell profile edit. Yet both command documents used to instruct
# the assistant to run `spec-kit-jira config` and `spec-kit-jira feature` as bare
# names. In a consuming repository no such command exists — which is precisely
# the reported "spec-kit-jira CLI not installed" symptom, generated by following
# the instructions as written.
#
# So the check is on the DOCUMENTS, not on the scripts: they are what the
# assistant follows, and a wrong instruction there produces a wrong action every
# time, on every machine.

setup() {
  ROOT="${BATS_TEST_DIRNAME}/../../.."
  DOCS_DIR="${ROOT}/commands"
  mapfile -t DOCS < <(find "${DOCS_DIR}" -name '*.md' -type f | LC_ALL=C sort)
  BASH_ENTRY='.specify/extensions/jira-mirror/scripts/bash/spec-kit-jira.sh'
  PWSH_ENTRY='.specify/extensions/jira-mirror/scripts/powershell/spec-kit-jira.ps1'
}

@test "there are four command documents, one per declared command" {
  [ "${#DOCS[@]}" -eq 4 ]
}

@test "no command document invokes a bare spec-kit-jira name (FR-014)" {
  local doc bad
  for doc in "${DOCS[@]}"; do
    bad="$(grep -nE '(^|[^/])spec-kit-jira(\.sh|\.ps1)?[[:space:]]+(config|reconcile|mention|feature)\b' "${doc}" || true)"
    if [[ -n "${bad}" ]]; then
      printf '%s invokes the bridge by a bare name:\n%s\n' "${doc}" "${bad}" >&2
      return 1
    fi
  done
}

@test "every command document names BOTH per-port entry points (FR-013, R6)" {
  # Naming only one port would leave the operator on the other one with an
  # instruction that cannot work — and the two ports are required to behave
  # identically (Constitution VI).
  local doc
  for doc in "${DOCS[@]}"; do
    grep -qF "${BASH_ENTRY}" "${doc}" || {
      printf '%s does not name the Bash entry point\n' "${doc}" >&2
      return 1
    }
    grep -qF "${PWSH_ENTRY}" "${doc}" || {
      printf '%s does not name the PowerShell entry point\n' "${doc}" >&2
      return 1
    }
  done
}

@test "every command document states the host-selection rule (FR-013)" {
  # Two paths with no rule for choosing between them is an invitation to guess.
  local doc
  for doc in "${DOCS[@]}"; do
    grep -qiE 'windows' "${doc}" || {
      printf '%s names the two entry points but no host-selection rule\n' "${doc}" >&2
      return 1
    }
  done
}

@test "both named entry points exist at the paths the documents spell (FR-012)" {
  # The paths are relative to the INSTALLED extension root, which is this
  # repository's root at development time.
  [ -f "${ROOT}/${BASH_ENTRY#.specify/extensions/jira-mirror/}" ]
  [ -f "${ROOT}/${PWSH_ENTRY#.specify/extensions/jira-mirror/}" ]
}

@test "every command document invokes the Bash entry point through the interpreter (026 FR-016, C2.3)" {
  # A zip install on a host below 0.14.3 does not restore the executable bit
  # (research R3), so a bare-path invocation can fail with "permission denied"
  # on an entirely intact install. `bash <path>` works either way.
  #
  # Only lines shaped as an actual invocation — the path followed by a
  # subcommand or flag — are checked; the table naming the entry point and the
  # fallback block naming the missing path are descriptive, not invocations.
  local doc invocations bad
  local pattern="${BASH_ENTRY//./\\.}[[:space:]]+(--help|config|reconcile|feature|mention)"
  for doc in "${DOCS[@]}"; do
    invocations="$(grep -nE "${pattern}" "${doc}" || true)"
    [[ -z "${invocations}" ]] && continue
    bad="$(grep -vE "bash ${pattern}" <<< "${invocations}" || true)"
    if [[ -n "${bad}" ]]; then
      printf '%s invokes the Bash entry point without the "bash " interpreter prefix:\n%s\n' "${doc}" "${bad}" >&2
      return 1
    fi
  done
}

@test "at least one command document demonstrates the interpreter-prefixed invocation" {
  local doc found=0
  for doc in "${DOCS[@]}"; do
    grep -qF "bash ${BASH_ENTRY}" "${doc}" && found=1
  done
  [ "${found}" -eq 1 ]
}

@test "no command document requires the executable bit to have survived (026 FR-016)" {
  local doc
  for doc in "${DOCS[@]}"; do
    grep -qiE 'is not executable' "${doc}" && {
      printf '%s still treats a lost executable bit as a fatal cause\n' "${doc}" >&2
      return 1
    }
  done
  true
}

@test "no command document tells the assistant to install anything machine-wide (FR-008)" {
  local doc bad
  for doc in "${DOCS[@]}"; do
    bad="$(grep -nE '(brew install spec-kit|npm i(nstall)? -g|pip install spec-kit|add to your PATH|export PATH=)' "${doc}" || true)"
    if [[ -n "${bad}" ]]; then
      printf '%s instructs a machine-wide install, which FR-008 forbids:\n%s\n' "${doc}" "${bad}" >&2
      return 1
    fi
  done
}
