#!/usr/bin/env bats
# T036 [US4] — The documented procedures invoke a bridge that exists (FR-014,
# research R6).
#
# `specify extension add` copies this repository into the consuming repository's
# `.specify/extensions/jira/` and installs NOTHING on the machine: no binary, no
# PATH entry, no shell profile edit. Yet both command documents used to instruct
# the assistant to run `spec-kit-jira config` and `spec-kit-jira feature` as bare
# names. In a consuming repository no such command exists — which is precisely
# the reported "spec-kit-jira CLI not installed" symptom, generated by following
# the instructions as written.
#
# So the check is on the DOCUMENTS, not on the scripts: they are what the
# assistant follows, and a wrong instruction there produces a wrong action every
# time, on every machine.

setup() {
  ROOT="${BATS_TEST_DIRNAME}/../../.."
  DOCS_DIR="${ROOT}/commands"
  mapfile -t DOCS < <(find "${DOCS_DIR}" -name '*.md' -type f | LC_ALL=C sort)
  BASH_ENTRY='.specify/extensions/jira/scripts/bash/spec-kit-jira.sh'
  PWSH_ENTRY='.specify/extensions/jira/scripts/powershell/spec-kit-jira.ps1'
}

@test "there are three command documents, one per declared command" {
  [ "${#DOCS[@]}" -eq 3 ]
}

@test "no command document invokes a bare spec-kit-jira name (FR-014)" {
  local doc bad
  for doc in "${DOCS[@]}"; do
    bad="$(grep -nE '(^|[^/])spec-kit-jira(\.sh|\.ps1)?[[:space:]]+(config|reconcile|mention|feature)\b' "${doc}" || true)"
    if [[ -n "${bad}" ]]; then
      printf '%s invokes the bridge by a bare name:\n%s\n' "${doc}" "${bad}" >&2
      return 1
    fi
  done
}

@test "every command document names BOTH per-port entry points (FR-013, R6)" {
  # Naming only one port would leave the operator on the other one with an
  # instruction that cannot work — and the two ports are required to behave
  # identically (Constitution VI).
  local doc
  for doc in "${DOCS[@]}"; do
    grep -qF "${BASH_ENTRY}" "${doc}" || {
      printf '%s does not name the Bash entry point\n' "${doc}" >&2
      return 1
    }
    grep -qF "${PWSH_ENTRY}" "${doc}" || {
      printf '%s does not name the PowerShell entry point\n' "${doc}" >&2
      return 1
    }
  done
}

@test "every command document states the host-selection rule (FR-013)" {
  # Two paths with no rule for choosing between them is an invitation to guess.
  local doc
  for doc in "${DOCS[@]}"; do
    grep -qiE 'windows' "${doc}" || {
      printf '%s names the two entry points but no host-selection rule\n' "${doc}" >&2
      return 1
    }
  done
}

@test "both named entry points exist at the paths the documents spell (FR-012)" {
  # The paths are relative to the INSTALLED extension root, which is this
  # repository's root at development time.
  [ -f "${ROOT}/${BASH_ENTRY#.specify/extensions/jira/}" ]
  [ -f "${ROOT}/${PWSH_ENTRY#.specify/extensions/jira/}" ]
}

@test "the Bash entry point is executable — invoking it by path requires it (FR-012)" {
  # Committed as 0644, every documented invocation would fail with "permission
  # denied" in a freshly installed repository, while the file plainly exists.
  [ -x "${ROOT}/scripts/bash/spec-kit-jira.sh" ]
}

@test "no command document tells the assistant to install anything machine-wide (FR-008)" {
  local doc bad
  for doc in "${DOCS[@]}"; do
    bad="$(grep -nE '(brew install spec-kit|npm i(nstall)? -g|pip install spec-kit|add to your PATH|export PATH=)' "${doc}" || true)"
    if [[ -n "${bad}" ]]; then
      printf '%s instructs a machine-wide install, which FR-008 forbids:\n%s\n' "${doc}" "${bad}" >&2
      return 1
    fi
  done
}
